### ISSUE TITLE
GitHub over SSH stop working in >= 19.3

### ISSUE THREAD

**Issue by mario-fuentes** [gocd/docker-gocd-server#83] opened 2019-06-21 13:56 UTC
Hi!, I'm upgrading our GoCD instance from 18.x series to 19.x, but I realize that from 19.3.0 version the GitHub over SSH stop working.  We're mounting the **/home/go** directory including the **.ssh** directory with the RSA keys to authenticate on GitHub and clone our Pipelines YAML files.  I tried with all 19.x docker versiones the the fellow result:
- 18.12 -> Work fine
- 19.1 -> Work fine
- 19.2 -> Work fine
- 19.3 -> Error
- 19.4 -> Error
- 19.5 -> Error

I receive the same error in versions 19.3, 19.4 and 19.5, so I suppose that a change in any package version is producing the error.

`There was an error parsing this configuration repository:
MODIFICATION CHECK FAILED FOR MATERIAL: URL: GIT@GITHUB.COM:<USER>/<REPO>.GIT, BRANCH: MASTER
NO PIPELINES ARE AFFECTED BY THIS MATERIAL, PERHAPS THIS MATERIAL IS UNUSED.
Failed to run git clone command STDERR: Cloning into '/go-working-dir/pipelines/flyweight/dd24529d-bd6e-491e-a53c-a8b0e1c32b82'...
STDERR: Connection to github.com closed by remote host.
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.`

Also I tested the connection to GitHub using _ssh -T git@github.com_ with the same results (doesn't work in 19.[3, 4, 5])

Any idea?

**Comment by mario-fuentes** [comment] 2019-06-21 19:50
I found that the situation is produced by a change in OpenSSH 7.8p1 and applying this config is working again: https://bugs.archlinux.org/task/59826#comment172612

**Comment by ketan** [comment] 2019-06-23 04:15
Thank you for confirming. Closing this issue because it is not caused by GoCD.

**Closed by ketan** 2019-06-23 04:15 UTC
